FROM ubuntu:20.04

# install some dependencies
# Note: to suppress interactive menu of tzdata, DEBIAN_FRONTEND must be set
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y \
    	antlr4 && \
    rm -rf /var/lib/apt/lists
